# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginPageUi(object):
    def setupUi(self, LoginPageUi):
        LoginPageUi.setObjectName("LoginPageUi")
        LoginPageUi.resize(370, 572)
        self.centralwidget = QtWidgets.QWidget(LoginPageUi)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
                                 "\n"
                                 "    background-color: rgb(56, 58, 89);\n"
                                 "    border-radius: 30px;\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(310, 5, 40, 40))
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "    \n"
                                      "    background-color: rgb(56, 58, 89);\n"
                                      "    border-style: none;\n"
                                      "    border-radius: 15px;\n"
                                      "    \n"
                                      "}\n"
                                      "")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 200, 141, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(241, 85, 255);")
        self.label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(10, 269, 341, 30))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
                                    "    background-color: rgb(56, 58, 89);\n"
                                    "    border-radius:10px;\n"
                                    "    border: 1px solid rgb(98, 78, 159);\n"
                                    "    color:white;\n"
                                    "}")
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(0, 70, 351, 151))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(241, 85, 255);\n"
                                   "")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 350, 141, 28))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
                                        "    border-style:none;\n"
                                        "    border-radius: 10px;\n"
                                        "    font-weight: bold;\n"
                                        "color:white;\n"
                                        "    background-color: rgb(149, 72, 172);\n"
                                        "}\n"
                                        "QPushButton::hover{\n"
                                        "border: 0.5px solid white;\n"
                                        "}\n"
                                        "")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 300, 341, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 44, 58);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.frame)
        LoginPageUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginPageUi)
        QtCore.QMetaObject.connectSlotsByName(LoginPageUi)

    def retranslateUi(self, LoginPageUi):
        _translate = QtCore.QCoreApplication.translate
        LoginPageUi.setWindowTitle(_translate("LoginPageUi", "Login"))
        self.label.setText(_translate("LoginPageUi", "Password:"))
        self.label_2.setText(_translate("LoginPageUi", "<strong>Book</strong>Family"))
        self.pushButton_2.setText(_translate("LoginPageUi", "Log in"))
        self.label_3.setText(_translate("LoginPageUi", "Incorrect password"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    LoginPageUi = QtWidgets.QMainWindow()
    ui = Ui_LoginPageUi()
    ui.setupUi(LoginPageUi)
    LoginPageUi.show()
    sys.exit(app.exec_())
