# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 500)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 500))
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toggleButton = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleButton.sizePolicy().hasHeightForWidth())
        self.toggleButton.setSizePolicy(sizePolicy)
        self.toggleButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toggleButton.setStyleSheet("border-style:none;\n"
                                        "")
        self.toggleButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/toggle_menu_disabled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggleButton.setIcon(icon)
        self.toggleButton.setIconSize(QtCore.QSize(50, 30))
        self.toggleButton.setObjectName("toggleButton")
        self.verticalLayout_2.addWidget(self.toggleButton)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LogoText = QtWidgets.QLabel(self.frame_top)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.LogoText.setFont(font)
        self.LogoText.setStyleSheet("color: rgb(238, 159, 0);")
        self.LogoText.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.LogoText.setObjectName("LogoText")
        #self.LogoText.setMinimumSize(QtCore.QSize(0,40))
        self.horizontalLayout_3.addWidget(self.LogoText)
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setStyleSheet("QPushButton{\n"
                                           "color:white;\n"
                                           "border-style:none;\n"
                                           "}")
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_add_book_page = QtWidgets.QPushButton(self.frame_top_menus)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_add_book_page.setFont(font)
        self.btn_add_book_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/add_book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_book_page.setIcon(icon1)
        self.btn_add_book_page.setIconSize(QtCore.QSize(25, 25))
        self.btn_add_book_page.setObjectName("btn_add_book_page")
        self.verticalLayout_4.addWidget(self.btn_add_book_page, 0, QtCore.Qt.AlignLeft)
        self.btn_delete_book_page = QtWidgets.QPushButton(self.frame_top_menus)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_delete_book_page.setFont(font)
        self.btn_delete_book_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/delete_book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete_book_page.setIcon(icon2)
        self.btn_delete_book_page.setIconSize(QtCore.QSize(25, 25))
        self.btn_delete_book_page.setObjectName("btn_delete_book_page")
        self.verticalLayout_4.addWidget(self.btn_delete_book_page, 0, QtCore.Qt.AlignLeft)
        self.btn_view_books_page = QtWidgets.QPushButton(self.frame_top_menus)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_view_books_page.setFont(font)
        self.btn_view_books_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icons/view_books.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_view_books_page.setIcon(icon3)
        self.btn_view_books_page.setIconSize(QtCore.QSize(23, 25))
        self.btn_view_books_page.setObjectName("btn_view_books_page")
        self.verticalLayout_4.addWidget(self.btn_view_books_page, 0, QtCore.Qt.AlignLeft)
        self.btn_issue_book_to_student_page = QtWidgets.QPushButton(self.frame_top_menus)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_issue_book_to_student_page.setFont(font)
        self.btn_issue_book_to_student_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icons/issue_book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_issue_book_to_student_page.setIcon(icon4)
        self.btn_issue_book_to_student_page.setIconSize(QtCore.QSize(22, 25))
        self.btn_issue_book_to_student_page.setObjectName("btn_issue_book_to_student_page")
        self.verticalLayout_4.addWidget(self.btn_issue_book_to_student_page, 0, QtCore.Qt.AlignLeft)
        self.btn_return_book_page = QtWidgets.QPushButton(self.frame_top_menus)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_return_book_page.setFont(font)
        self.btn_return_book_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Icons/return_book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_return_book_page.setIcon(icon5)
        self.btn_return_book_page.setIconSize(QtCore.QSize(25, 25))
        self.btn_return_book_page.setObjectName("btn_return_book_page")
        self.verticalLayout_4.addWidget(self.btn_return_book_page, 0, QtCore.Qt.AlignLeft)
        self.btn_add_student_page = QtWidgets.QPushButton(self.frame_top_menus)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_add_student_page.setFont(font)
        self.btn_add_student_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Icons/add-user-25.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_student_page.setIcon(icon6)
        self.btn_add_student_page.setIconSize(QtCore.QSize(25, 25))
        self.btn_add_student_page.setObjectName("btn_add_student_page")
        self.verticalLayout_4.addWidget(self.btn_add_student_page, 0, QtCore.Qt.AlignLeft)
        self.btn_view_students_page = QtWidgets.QPushButton(self.frame_top_menus)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(12)
        self.btn_view_students_page.setFont(font)
        self.btn_view_students_page.setStyleSheet("color:white;")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Icons/icons8-user-account-25.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_view_students_page.setIcon(icon7)
        self.btn_view_students_page.setIconSize(QtCore.QSize(25, 25))
        self.btn_view_students_page.setObjectName("btn_view_students_page")
        self.verticalLayout_4.addWidget(self.btn_view_students_page, 0, QtCore.Qt.AlignLeft)
        self.btn_spam_debtors_page = QtWidgets.QPushButton(self.frame_top_menus)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.btn_spam_debtors_page.setFont(font)
        self.btn_spam_debtors_page.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Icons/spam_debtors.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_spam_debtors_page.setIcon(icon8)
        self.btn_spam_debtors_page.setObjectName("btn_spam_debtors_page")
        self.verticalLayout_4.addWidget(self.btn_spam_debtors_page, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_3.addWidget(self.frame_top_menus)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setStyleSheet("color:white;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.add_book_page = QtWidgets.QWidget()
        self.add_book_page.setObjectName("add_book_page")
        self.gridLayout = QtWidgets.QGridLayout(self.add_book_page)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.add_book_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.add_book_page)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:white;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.add_book_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1, QtCore.Qt.AlignRight)
        self.label_4 = QtWidgets.QLabel(self.add_book_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 1, QtCore.Qt.AlignRight)
        self.label_3 = QtWidgets.QLabel(self.add_book_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1, QtCore.Qt.AlignRight)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 4, 1, 1)
        self.edit_Title = QtWidgets.QLineEdit(self.add_book_page)
        self.edit_Title.setMinimumSize(QtCore.QSize(0, 30))
        self.edit_Title.setStyleSheet("QLineEdit{\n"
                                      "    color:white;\n"
                                      "    border-style:none;\n"
                                      "    border-radius:10px;\n"
                                      "    border:1px solid white;\n"
                                      "}\n"
                                      "QLineEdit:focus{\n"
                                      "        border:1px solid rgb(238, 159, 0);\n"
                                      "}")
        self.edit_Title.setObjectName("edit_Title")
        self.gridLayout.addWidget(self.edit_Title, 2, 2, 1, 2)
        self.frame_10 = QtWidgets.QFrame(self.add_book_page)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame = QtWidgets.QFrame(self.frame_10)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setStyleSheet("QPushButton{\n"
                                 "    color:white;\n"
                                 "    border-style:none;\n"
                                 "    border:1px solid rgb(238, 159, 0); \n"
                                 "    border-radius: 10px;\n"
                                 "}\n"
                                 "QPushButton::hover{\n"
                                 "    background-color: rgb(238, 159, 0); \n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.verticalLayout_10.addWidget(self.frame)
        self.err_1 = QtWidgets.QLabel(self.frame_10)
        self.err_1.setMaximumSize(QtCore.QSize(16777215, 30))
        self.err_1.setStyleSheet("background-color: rgb(255, 39, 39);")
        self.err_1.setAlignment(QtCore.Qt.AlignCenter)
        self.err_1.setObjectName("err_1")
        self.verticalLayout_10.addWidget(self.err_1)
        self.gridLayout.addWidget(self.frame_10, 6, 2, 1, 1)
        self.edit_Id = QtWidgets.QLineEdit(self.add_book_page)
        self.edit_Id.setMinimumSize(QtCore.QSize(0, 30))
        self.edit_Id.setMaximumSize(QtCore.QSize(12312312, 16777215))
        self.edit_Id.setStyleSheet("QLineEdit{\n"
                                   "    color:white;\n"
                                   "    border-style:none;\n"
                                   "    border-radius:10px;\n"
                                   "    border:1px solid white;\n"
                                   "}\n"
                                   "QLineEdit:focus{\n"
                                   "        border:1px solid rgb(238, 159, 0);\n"
                                   "}")
        self.edit_Id.setObjectName("edit_Id")
        self.gridLayout.addWidget(self.edit_Id, 5, 2, 1, 1)
        self.edit_Genre = QtWidgets.QLineEdit(self.add_book_page)
        self.edit_Genre.setMinimumSize(QtCore.QSize(0, 30))
        self.edit_Genre.setStyleSheet("QLineEdit{\n"
                                      "    color:white;\n"
                                      "    border-style:none;\n"
                                      "    border-radius:10px;\n"
                                      "    border:1px solid white;\n"
                                      "}\n"
                                      "QLineEdit:focus{\n"
                                      "        border:1px solid rgb(238, 159, 0);\n"
                                      "}")
        self.edit_Genre.setObjectName("edit_Genre")
        self.gridLayout.addWidget(self.edit_Genre, 4, 2, 1, 2)
        self.edit_Author = QtWidgets.QLineEdit(self.add_book_page)
        self.edit_Author.setMinimumSize(QtCore.QSize(0, 30))
        self.edit_Author.setStyleSheet("QLineEdit{\n"
                                       "    color:white;\n"
                                       "    border-style:none;\n"
                                       "    border-radius:10px;\n"
                                       "    border:1px solid white;\n"
                                       "}\n"
                                       "QLineEdit:focus{\n"
                                       "        border:1px solid rgb(238, 159, 0);\n"
                                       "}")
        self.edit_Author.setObjectName("edit_Author")
        self.gridLayout.addWidget(self.edit_Author, 3, 2, 1, 2)
        self.stackedWidget.addWidget(self.add_book_page)
        self.delete_book_page = QtWidgets.QWidget()
        self.delete_book_page.setObjectName("delete_book_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.delete_book_page)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_9 = QtWidgets.QFrame(self.delete_book_page)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_2 = QtWidgets.QFrame(self.frame_9)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setStyleSheet("QPushButton{\n"
                                   "    color:white;\n"
                                   "    border-style:none;\n"
                                   "    border:1px solid rgb(238, 159, 0); \n"
                                   "    border-radius: 10px;\n"
                                   "}\n"
                                   "QPushButton::hover{\n"
                                   "    background-color: rgb(238, 159, 0); \n"
                                   "}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.verticalLayout_9.addWidget(self.frame_2)
        self.err_2 = QtWidgets.QLabel(self.frame_9)
        self.err_2.setStyleSheet("background-color: rgb(255, 39, 39);")
        self.err_2.setAlignment(QtCore.Qt.AlignCenter)
        self.err_2.setObjectName("err_2")
        self.verticalLayout_9.addWidget(self.err_2)
        self.gridLayout_2.addWidget(self.frame_9, 4, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.delete_book_page)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(30)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:white;")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.delete_book_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:white;\n"
                                   "margin-right:1px;")
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 1, 1, 1, QtCore.Qt.AlignRight)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 3, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.delete_book_page)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
                                    "    color:white;\n"
                                    "    border-style:none;\n"
                                    "    border-radius:10px;\n"
                                    "    border:1px solid white;\n"
                                    "}\n"
                                    "QLineEdit:focus{\n"
                                    "        border:1px solid rgb(238, 159, 0);\n"
                                    "}")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 3, 2, 1, 1)
        self.stackedWidget.addWidget(self.delete_book_page)
        self.view_books_page = QtWidgets.QWidget()
        self.view_books_page.setObjectName("view_books_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.view_books_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.view_books_page)
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 250))
        self.tableWidget.setStyleSheet("QTableWidget {    \n"
                                       "background-color: rgb(39, 44, 54);\n"
                                       "padding: 10px;\n"
                                       "border-radius: 20px;\n"
                                       "gridline-color: rgb(44, 49, 60);\n"
                                       "border-bottom: 1px solid rgb(44, 49, 60);\n"
                                       "}\n"
                                       "QTableWidget::item{\n"
                                       "border-color: rgb(44, 49, 60);\n"
                                       "padding-left: 5px;\n"
                                       "padding-right: 5px;\n"
                                       "gridline-color: rgb(44, 49, 60);\n"
                                       "}\n"
                                       "QTableWidget::item:selected{\n"
                                       "background-color: rgb(85, 170, 255);\n"
                                       "}\n"
                                       "QScrollBar:horizontal {\n"
                                       "     border: none;\n"
                                       "    background: rgb(52, 59, 72);\n"
                                       "    height: 14px;\n"
                                       "    margin: 0px 21px 0 21px;\n"
                                       "    border-radius: 0px;\n"
                                       "}\n"
                                       " QScrollBar:vertical {\n"
                                       "    border: none;\n"
                                       "    background: rgb(52, 59, 72);\n"
                                       "    color:rgb(39, 44, 54);\n"
                                       "    width: 14px;\n"
                                       "    \n"
                                       "    border-radius: 0px;\n"
                                       " }\n"
                                       "QHeaderView::section{\n"
                                       "    Background-color: rgb(39, 44, 54);\n"
                                       "    max-width: 30px;\n"
                                       "    border: 1px solid rgb(44, 49, 60);\n"
                                       "    border-style: none;\n"
                                       "    border-bottom: 1px solid rgb(44, 49, 60);\n"
                                       "    border-right: 1px solid rgb(44, 49, 60);\n"
                                       "}\n"
                                       "QTableWidget::horizontalHeader {    \n"
                                       "    background-color: rgb(81, 255, 0);\n"
                                       "}\n"
                                       "QHeaderView::section:horizontal\n"
                                       "{\n"
                                       "    border: 1px solid rgb(32, 34, 42);\n"
                                       "    background-color: rgb(27, 29, 35);\n"
                                       "    padding: 3px;\n"
                                       "    border-top-left-radius: 7px;\n"
                                       "    border-top-right-radius: 7px;\n"
                                       "}\n"
                                       "QHeaderView::section:vertical\n"
                                       "{\n"
                                       "    border: 1px solid rgb(44, 49, 60);\n"
                                       "}")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setRowCount(16)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(135)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.tableWidget, 6, 0, 1, 4)
        self.label_9 = QtWidgets.QLabel(self.view_books_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:white;")
        self.label_9.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 1, 3, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.view_books_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color:white;")
        self.label_35.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_3.addWidget(self.label_35, 4, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.view_books_page)
        self.label_36.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color:white;\n"
                                    "")
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_3.addWidget(self.label_36, 0, 1, 1, 2)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.view_books_page)
        self.lineEdit_12.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_12.setStyleSheet("QLineEdit{\n"
                                       "    color:white;\n"
                                       "    border-style:none;\n"
                                       "    border-radius:10px;\n"
                                       "    border:1px solid white;\n"
                                       "}\n"
                                       "QLineEdit:focus{\n"
                                       "        border:1px solid rgb(238, 159, 0);\n"
                                       "}")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_3.addWidget(self.lineEdit_12, 4, 2, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.view_books_page)
        self.lineEdit_11.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_11.setStyleSheet("QLineEdit{\n"
                                       "    color:white;\n"
                                       "    border-style:none;\n"
                                       "    border-radius:10px;\n"
                                       "    border:1px solid white;\n"
                                       "}\n"
                                       "QLineEdit:focus{\n"
                                       "        border:1px solid rgb(238, 159, 0);\n"
                                       "}")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_3.addWidget(self.lineEdit_11, 1, 2, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.view_books_page)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_17.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("QPushButton{\n"
                                         "    color:white;\n"
                                         "    border-style:none;\n"
                                         "    border:1px solid rgb(238, 159, 0); \n"
                                         "    border-radius: 10px;\n"
                                         "}\n"
                                         "QPushButton::hover{\n"
                                         "    background-color: rgb(238, 159, 0); \n"
                                         "}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_9.addWidget(self.pushButton_17)
        self.gridLayout_3.addWidget(self.frame_11, 7, 2, 1, 1)
        self.stackedWidget.addWidget(self.view_books_page)
        self.view_students_page = QtWidgets.QWidget()
        self.view_students_page.setObjectName("view_students_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.view_students_page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.view_students_page)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_5.setStyleSheet("QLineEdit{\n"
                                      "    color:white;\n"
                                      "    border-style:none;\n"
                                      "    border-radius:10px;\n"
                                      "    border:1px solid white;\n"
                                      "}\n"
                                      "QLineEdit:focus{\n"
                                      "        border:1px solid rgb(238, 159, 0);\n"
                                      "}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_5.addWidget(self.lineEdit_5, 1, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.view_students_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 1, 3, 1, 1)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.view_students_page)
        self.tableWidget_2.setMaximumSize(QtCore.QSize(16777215, 250))
        self.tableWidget_2.setStyleSheet("QTableWidget {    \n"
                                         "background-color: rgb(39, 44, 54);\n"
                                         "padding: 10px;\n"
                                         "border-radius: 20px;\n"
                                         "gridline-color: rgb(44, 49, 60);\n"
                                         "border-bottom: 1px solid rgb(44, 49, 60);\n"
                                         "}\n"
                                         "QTableWidget::item{\n"
                                         "border-color: rgb(44, 49, 60);\n"
                                         "padding-left: 5px;\n"
                                         "padding-right: 5px;\n"
                                         "gridline-color: rgb(44, 49, 60);\n"
                                         "}\n"
                                         "QTableWidget::item:selected{\n"
                                         "background-color: rgb(85, 170, 255);\n"
                                         "}\n"
                                         "QScrollBar:horizontal {\n"
                                         "     border: none;\n"
                                         "    background: rgb(52, 59, 72);\n"
                                         "    height: 14px;\n"
                                         "    margin: 0px 21px 0 21px;\n"
                                         "    border-radius: 0px;\n"
                                         "}\n"
                                         " QScrollBar:vertical {\n"
                                         "    border: none;\n"
                                         "    background: rgb(52, 59, 72);\n"
                                         "    color:rgb(39, 44, 54);\n"
                                         "    width: 14px;\n"
                                         "    \n"
                                         "    border-radius: 0px;\n"
                                         " }\n"
                                         "QHeaderView::section{\n"
                                         "    Background-color: rgb(39, 44, 54);\n"
                                         "    max-width: 30px;\n"
                                         "    border: 1px solid rgb(44, 49, 60);\n"
                                         "    border-style: none;\n"
                                         "    border-bottom: 1px solid rgb(44, 49, 60);\n"
                                         "    border-right: 1px solid rgb(44, 49, 60);\n"
                                         "}\n"
                                         "QTableWidget::horizontalHeader {    \n"
                                         "    background-color: rgb(81, 255, 0);\n"
                                         "}\n"
                                         "QHeaderView::section:horizontal\n"
                                         "{\n"
                                         "    border: 1px solid rgb(32, 34, 42);\n"
                                         "    background-color: rgb(27, 29, 35);\n"
                                         "    padding: 3px;\n"
                                         "    border-top-left-radius: 7px;\n"
                                         "    border-top-right-radius: 7px;\n"
                                         "}\n"
                                         "QHeaderView::section:vertical\n"
                                         "{\n"
                                         "    border: 1px solid rgb(44, 49, 60);\n"
                                         "}")
        self.tableWidget_2.setRowCount(1)
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.gridLayout_5.addWidget(self.tableWidget_2, 2, 0, 1, 4)
        self.label_5 = QtWidgets.QLabel(self.view_students_page)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 1, 1, 2)
        self.pushButton_11 = QtWidgets.QPushButton(self.view_students_page)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton{\n"
                                         "    color:white;\n"
                                         "    border-style:none;\n"
                                         "    border:1px solid rgb(238, 159, 0); \n"
                                         "    border-radius: 10px;\n"
                                         "}\n"
                                         "QPushButton::hover{\n"
                                         "    background-color: rgb(238, 159, 0); \n"
                                         "}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_5.addWidget(self.pushButton_11, 3, 1, 1, 2)
        self.stackedWidget.addWidget(self.view_students_page)
        self.issue_book_page = QtWidgets.QWidget()
        self.issue_book_page.setObjectName("issue_book_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.issue_book_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.issue_book_page)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
                                      "    color:white;\n"
                                      "    border-style:none;\n"
                                      "    border-radius:10px;\n"
                                      "    border:1px solid white;\n"
                                      "}\n"
                                      "QLineEdit:focus{\n"
                                      "        border:1px solid rgb(238, 159, 0);\n"
                                      "}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_4.addWidget(self.lineEdit_3, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.issue_book_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color:white;")
        self.label_15.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 2, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 1, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.issue_book_page)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:white;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 1, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.issue_book_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:white;")
        self.label_14.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 1, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.issue_book_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 3, 1, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.issue_book_page)
        self.lineEdit_8.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_8.setStyleSheet("QLineEdit{\n"
                                      "    color:white;\n"
                                      "    border-style:none;\n"
                                      "    border-radius:10px;\n"
                                      "    border:1px solid white;\n"
                                      "}\n"
                                      "QLineEdit:focus{\n"
                                      "        border:1px solid rgb(238, 159, 0);\n"
                                      "}")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_4.addWidget(self.lineEdit_8, 3, 2, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.issue_book_page)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.frame_6)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setStyleSheet("QPushButton{\n"
                                   "    color:white;\n"
                                   "    border-style:none;\n"
                                   "    border:1px solid rgb(238, 159, 0); \n"
                                   "    border-radius: 10px;\n"
                                   "}\n"
                                   "QPushButton::hover{\n"
                                   "    background-color: rgb(238, 159, 0); \n"
                                   "}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.err_3 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.err_3.setFont(font)
        self.err_3.setStyleSheet("background-color: rgb(255, 39, 39);")
        self.err_3.setAlignment(QtCore.Qt.AlignCenter)
        self.err_3.setObjectName("err_3")
        self.verticalLayout_6.addWidget(self.err_3)
        self.gridLayout_4.addWidget(self.frame_6, 4, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.issue_book_page)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
                                      "    color:white;\n"
                                      "    border-style:none;\n"
                                      "    border-radius:10px;\n"
                                      "    border:1px solid white;\n"
                                      "}\n"
                                      "QLineEdit:focus{\n"
                                      "        border:1px solid rgb(238, 159, 0);\n"
                                      "}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_4.addWidget(self.lineEdit_2, 1, 2, 1, 1)
        self.stackedWidget.addWidget(self.issue_book_page)
        self.return_book_page = QtWidgets.QWidget()
        self.return_book_page.setObjectName("return_book_page")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.return_book_page)
        self.gridLayout_21.setObjectName("gridLayout_21")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem10, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.return_book_page)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:white;\n"
                                    "")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_21.addWidget(self.label_11, 0, 1, 1, 2)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem11, 1, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.return_book_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color:white;\n"
                                    "")
        self.label_16.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_21.addWidget(self.label_16, 1, 1, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.return_book_page)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
                                      "    color:white;\n"
                                      "    border-style:none;\n"
                                      "    border-radius:10px;\n"
                                      "    border:1px solid white;\n"
                                      "}\n"
                                      "QLineEdit:focus{\n"
                                      "        border:1px solid rgb(238, 159, 0);\n"
                                      "}")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_21.addWidget(self.lineEdit_4, 1, 2, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.return_book_page)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.frame_7)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_4.setStyleSheet("QPushButton{\n"
                                   "    color:white;\n"
                                   "    border-style:none;\n"
                                   "    border:1px solid rgb(238, 159, 0); \n"
                                   "    border-radius: 10px;\n"
                                   "}\n"
                                   "QPushButton::hover{\n"
                                   "    background-color: rgb(238, 159, 0); \n"
                                   "}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_7.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_7.addWidget(self.pushButton_8)
        self.verticalLayout_7.addWidget(self.frame_4)
        self.err_4 = QtWidgets.QLabel(self.frame_7)
        self.err_4.setStyleSheet("background-color: rgb(255, 39, 39);")
        self.err_4.setAlignment(QtCore.Qt.AlignCenter)
        self.err_4.setObjectName("err_4")
        self.verticalLayout_7.addWidget(self.err_4)
        self.gridLayout_21.addWidget(self.frame_7, 2, 1, 1, 2)
        self.stackedWidget.addWidget(self.return_book_page)
        self.add_student_page = QtWidgets.QWidget()
        self.add_student_page.setObjectName("add_student_page")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.add_student_page)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_39 = QtWidgets.QLabel(self.add_student_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_6.addWidget(self.label_39, 4, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.add_student_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_6.addWidget(self.label_40, 3, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.add_student_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_6.addWidget(self.label_37, 1, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.add_student_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_6.addWidget(self.label_38, 2, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem12, 1, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem13, 1, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.add_student_page)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_6.addWidget(self.label_13, 5, 1, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.add_student_page)
        self.lineEdit_15.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_15.setStyleSheet("QLineEdit{\n"
                                       "    color:white;\n"
                                       "    border-style:none;\n"
                                       "    border-radius:10px;\n"
                                       "    border:1px solid white;\n"
                                       "}\n"
                                       "QLineEdit:focus{\n"
                                       "        border:1px solid rgb(238, 159, 0);\n"
                                       "}")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_6.addWidget(self.lineEdit_15, 4, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.add_student_page)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:white;")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 0, 1, 1, 2)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.add_student_page)
        self.lineEdit_13.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_13.setStyleSheet("QLineEdit{\n"
                                       "    color:white;\n"
                                       "    border-style:none;\n"
                                       "    border-radius:10px;\n"
                                       "    border:1px solid white;\n"
                                       "}\n"
                                       "QLineEdit:focus{\n"
                                       "        border:1px solid rgb(238, 159, 0);\n"
                                       "}")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_6.addWidget(self.lineEdit_13, 1, 2, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.add_student_page)
        self.lineEdit_16.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_16.setStyleSheet("QLineEdit{\n"
                                       "    color:white;\n"
                                       "    border-style:none;\n"
                                       "    border-radius:10px;\n"
                                       "    border:1px solid white;\n"
                                       "}\n"
                                       "QLineEdit:focus{\n"
                                       "        border:1px solid rgb(238, 159, 0);\n"
                                       "}")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_6.addWidget(self.lineEdit_16, 3, 2, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.add_student_page)
        self.lineEdit_14.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_14.setStyleSheet("QLineEdit{\n"
                                       "    color:white;\n"
                                       "    border-style:none;\n"
                                       "    border-radius:10px;\n"
                                       "    border:1px solid white;\n"
                                       "}\n"
                                       "QLineEdit:focus{\n"
                                       "        border:1px solid rgb(238, 159, 0);\n"
                                       "}")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_6.addWidget(self.lineEdit_14, 2, 2, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.add_student_page)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_6.setStyleSheet("QLineEdit{\n"
                                      "    color:white;\n"
                                      "    border-style:none;\n"
                                      "    border-radius:10px;\n"
                                      "    border:1px solid white;\n"
                                      "}\n"
                                      "QLineEdit:focus{\n"
                                      "        border:1px solid rgb(238, 159, 0);\n"
                                      "}")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_6.addWidget(self.lineEdit_6, 5, 2, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.add_student_page)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_5 = QtWidgets.QFrame(self.frame_8)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_5.setStyleSheet("QPushButton{\n"
                                   "    color:white;\n"
                                   "    border-style:none;\n"
                                   "    border:1px solid rgb(238, 159, 0); \n"
                                   "    border-radius: 10px;\n"
                                   "}\n"
                                   "QPushButton::hover{\n"
                                   "    background-color: rgb(238, 159, 0); \n"
                                   "}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_18.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_12.addWidget(self.pushButton_18)
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_19.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_12.addWidget(self.pushButton_19)
        self.verticalLayout_8.addWidget(self.frame_5)
        self.err_5 = QtWidgets.QLabel(self.frame_8)
        self.err_5.setStyleSheet("background-color: rgb(255, 39, 39);")
        self.err_5.setAlignment(QtCore.Qt.AlignCenter)
        self.err_5.setObjectName("err_5")
        self.verticalLayout_8.addWidget(self.err_5)
        self.gridLayout_6.addWidget(self.frame_8, 6, 1, 1, 2)
        self.stackedWidget.addWidget(self.add_student_page)
        self.spam_debtors_page = QtWidgets.QWidget()
        self.spam_debtors_page.setStyleSheet("QPushButton{\n"
                                             "    color:white;\n"
                                             "    border-style:none;\n"
                                             "    border:1px solid rgb(238, 159, 0); \n"
                                             "    border-radius: 10px;\n"
                                             "}\n"
                                             "QPushButton::hover{\n"
                                             "    background-color: rgb(238, 159, 0); \n"
                                             "}")
        self.spam_debtors_page.setObjectName("spam_debtors_page")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.spam_debtors_page)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.spam_debtors_page)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_8.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.spam_debtors_page)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_8.addWidget(self.pushButton_10)
        self.stackedWidget.addWidget(self.spam_debtors_page)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Book Family"))
        self.LogoText.setText(_translate("MainWindow", "<strong>Book Family</strong>"))
        self.btn_add_book_page.setText(_translate("MainWindow", "Add book"))
        self.btn_delete_book_page.setText(_translate("MainWindow", "Delete book"))
        self.btn_view_books_page.setText(_translate("MainWindow", "View books"))
        self.btn_issue_book_to_student_page.setText(_translate("MainWindow", "Issue book"))
        self.btn_return_book_page.setText(_translate("MainWindow", "Return book"))
        self.btn_add_student_page.setText(_translate("MainWindow", "Add student"))
        self.btn_view_students_page.setText(_translate("MainWindow", "View students"))
        self.btn_spam_debtors_page.setText(_translate("MainWindow", "Spam debtors    "))
        self.label.setText(_translate("MainWindow", "Publish year"))
        self.label_6.setText(_translate("MainWindow", "Add book"))
        self.label_2.setText(_translate("MainWindow", "Title"))
        self.label_4.setText(_translate("MainWindow", "Genre"))
        self.label_3.setText(_translate("MainWindow", "Author"))
        self.pushButton.setText(_translate("MainWindow", "Add"))
        self.pushButton_2.setText(_translate("MainWindow", "Cancel"))
        self.err_1.setText(_translate("MainWindow", "Emtpy entries"))
        self.pushButton_3.setText(_translate("MainWindow", "Delete"))
        self.pushButton_4.setText(_translate("MainWindow", "Cancel"))
        self.err_2.setText(_translate("MainWindow", "Empty entries"))
        self.label_7.setText(_translate("MainWindow", "Delete book"))
        self.label_8.setText(_translate("MainWindow", "Book ID"))
        self.label_9.setText(_translate("MainWindow", "Title"))
        self.label_35.setText(_translate("MainWindow", "Author"))
        self.label_36.setText(_translate("MainWindow", "View books"))
        self.pushButton_17.setText(_translate("MainWindow", "Find all books"))
        self.label_17.setText(_translate("MainWindow", "FIO:"))
        self.label_5.setText(_translate("MainWindow", "View students"))
        self.pushButton_11.setText(_translate("MainWindow", "View"))
        self.label_15.setText(_translate("MainWindow", "FIO"))
        self.label_10.setText(_translate("MainWindow", " Issue book"))
        self.label_14.setText(_translate("MainWindow", "Book ID"))
        self.label_19.setText(_translate("MainWindow", "Email"))
        self.pushButton_5.setText(_translate("MainWindow", "Issue"))
        self.pushButton_6.setText(_translate("MainWindow", "Cancel"))
        self.err_3.setText(_translate("MainWindow", "Empty ID"))
        self.label_11.setText(_translate("MainWindow", "Return book"))
        self.label_16.setText(_translate("MainWindow", "Book ID"))
        self.pushButton_7.setText(_translate("MainWindow", "Return"))
        self.pushButton_8.setText(_translate("MainWindow", "Cancel"))
        self.err_4.setText(_translate("MainWindow", "Empty Entries"))
        self.label_39.setText(_translate("MainWindow", "Instagram"))
        self.label_40.setText(_translate("MainWindow", "Third Name"))
        self.label_37.setText(_translate("MainWindow", "First Name"))
        self.label_38.setText(_translate("MainWindow", "Second Name"))
        self.label_13.setText(_translate("MainWindow", "Email"))
        self.label_12.setText(_translate("MainWindow", "Add student"))
        self.pushButton_18.setText(_translate("MainWindow", "Add"))
        self.pushButton_19.setText(_translate("MainWindow", "Cancel"))
        self.err_5.setText(_translate("MainWindow", "Empty Entries"))
        self.pushButton_9.setText(_translate("MainWindow", "Spam To Instagram"))
        self.pushButton_10.setText(_translate("MainWindow", "Spam To Email"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
